# Generated by Django 5.2 on 2025-04-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at_post_rate_post_upadated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upadated_at',
            new_name='updated_at',
        ),
    ]
